services: 
  ecommercelordjnux:
    build: ./
    ports:
        - "3017:3000"
    env_file:
        - .env
    depends_on:
        - postgresdb
    

  postgresdb:
    image: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: